name: Update Checker

env:
  REPO_URL: https://github.com/padavanonly/immortalwrt-mt798x-6.6
  REPO_BRANCH: openwrt-24.10-6.6

  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true


on:
  workflow_dispatch:
  schedule:
    - cron: 0 */18 * * *


jobs:
  check:
    runs-on: ubuntu-latest

    steps:

    # =========================
    # Get latest commit hash
    # =========================
    - name: Get latest commit hash
      id: getHash
      run: |
        git init repo
        cd repo

        git remote add origin $REPO_URL
        git fetch --depth=1 origin $REPO_BRANCH
        git checkout FETCH_HEAD

        echo "commitHash=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT


    # =========================
    # Load previous hash (artifact cache replacement)
    # =========================
    - name: Restore previous hash
      id: cacheHash
      uses: actions/cache@v4
      with:
        path: .commitHash
        key: commitHash-${{ env.REPO_BRANCH }}


    # =========================
    # Compare hash
    # =========================
    - name: Compare hashes
      id: compare
      run: |
        NEW="${{ steps.getHash.outputs.commitHash }}"

        if [ -f .commitHash ]; then
          OLD=$(cat .commitHash)
        else
          OLD=""
        fi

        echo "new=$NEW" >> $GITHUB_OUTPUT

        if [ "$NEW" != "$OLD" ]; then
          echo "changed=true" >> $GITHUB_OUTPUT
        else
          echo "changed=false" >> $GITHUB_OUTPUT
        fi


    # =========================
    # Save new hash
    # =========================
    - name: Save new hash
      if: steps.compare.outputs.changed == 'true'
      run: |
        echo "${{ steps.getHash.outputs.commitHash }}" > .commitHash


    # =========================
    # Trigger build
    # =========================
    - name: Trigger build
      if: steps.compare.outputs.changed == 'true'
      uses: peter-evans/repository-dispatch@v3
      with:
        token: ${{ github.token }}
        event-type: Source Code Update


    # =========================
    # cleanup
    # =========================
    - name: Delete workflow runs
      uses: Mattraks/delete-workflow-runs@v2
      with:
        retain_days: 0
        keep_minimum_runs: 2
