name: Update Checker

env:
  REPO_URL: https://github.com/padavanonly/immortalwrt-mt798x-6.6
  REPO_BRANCH: openwrt-24.10-6.6

  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true


on:
  workflow_dispatch:

  schedule:
    - cron: "0 */18 * * *"


jobs:
  check:

    runs-on: ubuntu-latest


    steps:

    # =========================
    # Checkout current repo
    # =========================
    - name: Checkout
      uses: actions/checkout@v4



    # =========================
    # Get upstream commit
    # =========================
    - name: Get latest commit hash
      id: getHash
      run: |

        git init upstream

        cd upstream

        git remote add origin $REPO_URL

        git fetch --depth=1 origin $REPO_BRANCH

        HASH=$(git rev-parse FETCH_HEAD)

        echo "hash=$HASH" >> $GITHUB_OUTPUT



    # =========================
    # Restore old hash
    # =========================
    - name: Restore hash
      uses: actions/cache@v4
      id: hash-cache
      with:

        path: .commitHash

        key: commit-${{ runner.os }}-${{ env.REPO_BRANCH }}-${{ github.run_id }}

        restore-keys: |
          commit-${{ runner.os }}-${{ env.REPO_BRANCH }}-



    # =========================
    # Compare
    # =========================
    - name: Compare
      id: compare
      run: |

        NEW="${{ steps.getHash.outputs.hash }}"


        if [ -f .commitHash ]; then

          OLD=$(cat .commitHash)

        else

          OLD=""

        fi


        echo "OLD=$OLD"

        echo "NEW=$NEW"



        if [ "$NEW" != "$OLD" ]; then

          echo "changed=true" >> $GITHUB_OUTPUT

        else

          echo "changed=false" >> $GITHUB_OUTPUT

        fi



    # =========================
    # Save new hash
    # =========================
    - name: Save new hash
      if: steps.compare.outputs.changed == 'true'
      run: |

        echo "${{ steps.getHash.outputs.hash }}" > .commitHash



    # =========================
    # Trigger OpenWrt build
    # =========================
    - name: Trigger build
      if: steps.compare.outputs.changed == 'true'

      uses: peter-evans/repository-dispatch@v3

      with:

        token: ${{ github.token }}

        event-type: Source Code Update



    # =========================
    # Cleanup
    # =========================
    - name: Delete workflow runs

      uses: Mattraks/delete-workflow-runs@v2

      with:

        retain_days: 0

        keep_minimum_runs: 2
