name: Update Checker

env:
  REPO_URL: https://github.com/padavanonly/immortalwrt-mt798x-6.6
  REPO_BRANCH: openwrt-24.10-6.6


on:
  workflow_dispatch:
  schedule:
    - cron: 0 */18 * * *


jobs:
  check:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout empty workspace
      run: |
        mkdir repo && cd repo
        git init
        git remote add origin $REPO_URL
        git fetch --depth=1 origin $REPO_BRANCH
        git checkout FETCH_HEAD

        echo "commitHash=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT
      id: getHash


    # =========================
    # cache compare (v4)
    # =========================
    - name: Compare Commit Hash
      id: cacheHash
      uses: actions/cache@v4
      with:
        path: .commitHash
        key: commitHash-${{ steps.getHash.outputs.commitHash }}


    - name: Save commit hash file
      if: steps.cacheHash.outputs.cache-hit != 'true'
      run: |
        echo "${{ steps.getHash.outputs.commitHash }}" > .commitHash


    # =========================
    # trigger build only when changed
    # =========================
    - name: Trigger build
      if: steps.cacheHash.outputs.cache-hit != 'true'
      uses: peter-evans/repository-dispatch@v2
      with:
        token: ${{ github.token }}
        event-type: Source Code Update


    # =========================
    # cleanup
    # =========================
    - name: Delete workflow runs
      uses: Mattraks/delete-workflow-runs@v2
      with:
        retain_days: 0
        keep_minimum_runs: 2
